Repository HisteriaMC/histeria-wiki, pull requests merged in 2023-12, with the labels that each got.

#211 Update resilient.md
  enchantements/resilient.md
Labels: bug

#210 Patch des screens et des descriptions des serveurs factions
  .assets/pictures/blackmarket.png
  .assets/pictures/faction1.png
  .assets/pictures/faction1v6-5.png
  .assets/pictures/faction2.png
  .assets/pictures/faction2v6-5.png
  .assets/pictures/faction3.png
  .assets/pictures/faction3v6-5.png
  .assets/pictures/gouffre.png
  .assets/pictures/jump.png
  .assets/pictures/jumpv6-5.png
  .assets/pictures/sorties-faction.png
  .assets/pictures/sortiesv6-5.png
  mondes/faction-servers.md
  mondes/faction1.md
  mondes/faction2.md
  mondes/faction3.md
Labels: documentation, enhancement

#216 Patch coffre arene
  .assets/blocks/chest-front.png
  mondes/arena-chest.md
Labels: bug, documentation

#219 Calice de Dionysos
  .assets/items/chalice.png
  objets/chalice.md
Labels: bug, documentation, enhancement

#221 Update hermes.md
  boss/hermes.md
Labels: typography

#222 Update poseidon.md
  boss/poseidon.md
Labels: typography

#223 Update item-pack.md
  objets/item-pack.md
Labels: documentation, enhancement

#224 Update des coffres d'arène
  .assets/blocks/chest-front.png
  mondes/arena-chest.md
Labels: bug

#231 Totem en histerite
  .assets/items/histerite-totem.png
  objets/histerite-totem.md
Labels: enhancement
