Repository HisteriaMC/histeria-wiki, pull requests merged in 2023-11, with the labels that each got.

#176 Update textures
  .assets/armors/histerite-boots.png
  .assets/armors/histerite-chestplate.png
  .assets/armors/histerite-helmet.png
  .assets/armors/histerite-leggings.png
  .assets/armors/nocturite-boots.png
  .assets/armors/nocturite-chestplate.png
  .assets/armors/nocturite-helmet.png
  .assets/armors/nocturite-leggings.png
  .assets/blocks/cactus.png
  .assets/blocks/fertilized-dirt.png
  .assets/blocks/histerite-anvil.png
  .assets/blocks/histerite-block.png
  .assets/blocks/histerite-ingot.png
  .assets/blocks/histerite-ore.png
  .assets/blocks/nocturite-block.png
  .assets/blocks/poison-obsidian.png
  .assets/blocks/random-ore.png
  .assets/blocks/renforced-obsidian.png
  .assets/blocks/spike.png
  .assets/items/banknote.png
  .assets/items/chest-finder.png
  .assets/items/dynamite.png
  .assets/items/forge-note.png
  .assets/items/hammer.png
  .assets/items/histerite-apple.png
  .assets/items/histerite-axe.png
  .assets/items/histerite-compress.png
  .assets/items/histerite-core.png
  .assets/items/histerite-hoe.png
  .assets/items/histerite-ingot.png
  .assets/items/histerite-pickaxe.png
  .assets/items/histerite-shovel.png
  .assets/items/histerite-stick.png
  .assets/items/histerite-sword.png
  .assets/items/jump-stick.png
  .assets/items/lottery-ticket.png
  .assets/items/nocturite-compress.png
  .assets/items/nocturite-core.png
  .assets/items/nocturite-crystal.png
  .assets/items/nocturite-fruit.png
  .assets/items/nocturite-seed.png
  .assets/items/shuriken.png
  .assets/items/speed-stick.png
  .assets/items/thunderbolt.png
Labels: documentation, enhancement

#194 Patch de différent pb de textures
  objets/histerite-compress.md
  objets/histerite-stick.md
  objets/seed-planter.md
Labels: documentation

#197 Update nocturite-chestplate.md
  armures/nocturite-chestplate.md
Labels: bug, enhancement

#202 Niveaux requis pour les crafts
  blocs/fertilized-dirt.md
  objets/hang-glider.md
  objets/heal-stick.md
  objets/histerite-apple.md
  objets/histerite-core.md
  objets/item-pack.md
  objets/jump-stick.md
  objets/speed-stick.md
  outils/grapnel.md
  outils/hammer.md
  outils/histerite-axe.md
  outils/histerite-hoe.md
  outils/histerite-pickaxe.md
  outils/histerite-shovel.md
  outils/histerite-sword.md
Labels: bug, enhancement

#203 Shield titre
  enchantements/shield.md
Labels: bug, enhancement, invalid

#204 Modifications du parchemin + orthographe lucky block
  blocs/lucky-block.md
  objets/forge-note.md
Labels: bug, enhancement

#205 Inversion utilités Éclair et Lyre
  objets/magic-lyre.md
  objets/zeus-flash.md
Labels: bug, enhancement
