Repository HisteriaMC/histeria-wiki, pull requests merged in 2023-03, with the labels that each got.

#5 Création de la catégorie "tools"
  .assets/armors/histerite-boots.png
  .assets/armors/histerite-chestplate.png
  .assets/armors/histerite-helmet.png
  .assets/armors/histerite-leggings.png
  .assets/armors/nocturite-boots.png
  .assets/armors/nocturite-chestplate.png
  .assets/armors/nocturite-helmet.png
  .assets/armors/nocturite-leggings.png
  .assets/items/forge-note.png
  .assets/items/hammer.png
  .assets/items/histerite-axe.png
  .assets/items/histerite-hoe.png
  .assets/items/histerite-ingot.png
  .assets/items/histerite-pickaxe.png
  .assets/items/histerite-shovel.png
  .assets/items/histerite-stick.png
  .assets/items/histerite-sword.png
  .assets/items/java-histerite-block.png
  .assets/items/java-histerite-ingot.png
  .assets/items/java-histerite-pickaxe.png
  .assets/items/java-histerite-stick.png
  .assets/items/nocturite-compress.png
  .assets/worlds/alpin_hook.png
  armors/histerite-boots.md
  armors/histerite-chestplate.md
  armors/histerite-helmet.md
  armors/histerite-leggings.md
  armors/nocturite-boots.md
  armors/nocturite-chestplate.md
  armors/nocturite-helmet.md
  armors/nocturite-leggings.md
  blocks/histerite-block.md
  items/forge-note.md
  items/histerite-pickaxe.md
  tools/hammer.md
  tools/histerite-axe.md
  tools/histerite-hoe.md
  tools/histerite-pickaxe.md
  tools/histerite-shovel.md
  tools/histerite-sword.md
Labels: documentation

#3 Ajout de la section boss/ mondes faction
  .assets/entities/boss/achilles.png
  .assets/entities/boss/apollo.png
  .assets/entities/boss/ares.png
  .assets/entities/boss/hades.png
  .assets/entities/boss/hermes.png
  .assets/entities/boss/poseidon.png
  .assets/entities/boss/zeus.png
  .assets/pictures/blackmarket.png
  .assets/pictures/bosstimer.png
  .assets/pictures/colosseum.png
  .assets/pictures/faction1.png
  .assets/pictures/faction2.png
  .assets/pictures/faction3.png
  .assets/pictures/gouffre.png
  .assets/pictures/jump.png
  .assets/pictures/lobby.png
  .assets/pictures/sorties-faction.png
  boss/ares.md
  boss/explication-générale.md
  boss/hermes.md
  boss/poseidon.md
  boss/zeus.md
  worlds/faction1.md
  worlds/faction2.md
  worlds/faction3.md
  worlds/serveurs-faction.md
Labels: documentation

#10 Ajout d'un parser a la pipeline
  .bash/file-format-checker.sh
  .github/workflows/test-wiki.yml
Labels: enhancement

#4 Added Cave-Block page
  .assets/blocks/cave-block.png
  .assets/blocks/glass.png
  blocks/cave-block.md
Labels: documentation

#129 Enchantements d'arène
  enchants/eclipse.md
  enchants/fusion.md
  enchants/hypothermia.md
  enchants/lunarstrike.md
  enchants/magic.md
  enchants/permaflame.md
  enchants/revive.md
Labels: documentation

#12 Ajout des enchantements
  .assets/items/enchanted-book.png
  .assets/items/nocturite-core.png
  armors/nocturite-boots.md
  armors/nocturite-chestplate.md
  armors/nocturite-helmet.md
  armors/nocturite-leggings.md
  enchants/adrenaline.md
  enchants/attraction.md
  enchants/bleeding.md
  enchants/demonic.md
  enchants/dragonbreath.md
  enchants/fatigue.md
  enchants/fluctuation.md
  enchants/freeze.md
  enchants/hunger.md
  enchants/narcotic.md
  enchants/reborn.md
  enchants/rust.md
  enchants/soulsteal.md
  enchants/split.md
  enchants/strike.md
  enchants/vampire.md
Labels: documentation

#132 Modifications des boss
  boss/ares.md
  boss/fonctionnement-des-boss.md
  boss/hermes.md
  boss/poseidon.md
  boss/zeus.md
Labels: documentation, enhancement, typography

#130 Ajout des enchantements de boss
  enchants/bloodignite.md
  enchants/bosskiller.md
  enchants/clone.md
  enchants/execution.md
  enchants/featherwalk.md
  enchants/omniscient.md
  enchants/outrage.md
  enchants/peacekeeper.md
  enchants/reset.md
  enchants/tsunami.md
Labels: documentation

#11 Commandes Générales
  commands/economy-commands.md
  commands/faction-commandes.md
  commands/general-commands.md
  commands/graded-commands.md
  commands/home-and-tp-commands.md
Labels: documentation

#137 Correction image de craft armure noc
  armors/nocturite-boots.md
  armors/nocturite-chestplate.md
  armors/nocturite-helmet.md
  armors/nocturite-leggings.md
Labels: bug

#139 Ajout icon cave block
  blocks/cave-block.md
Labels: documentation, enhancement

#140 Modif icon enchants
  .assets/items/enchanted-book.png
  .assets/items/enchanted-book.webp
  enchants/adrenaline.md
  enchants/attraction.md
  enchants/autodestruct.md
  enchants/blasphemy.md
  enchants/bleeding.md
  enchants/bloodignite.md
  enchants/bosskiller.md
  enchants/clone.md
  enchants/conceal.md
  enchants/demonic.md
  enchants/dodge.md
  enchants/dragonbreath.md
  enchants/eclipse.md
  enchants/execution.md
  enchants/fatigue.md
  enchants/featherwalk.md
  enchants/fireproof.md
  enchants/fluctuation.md
  enchants/freeze.md
  enchants/fusion.md
  enchants/hunger.md
  enchants/hypothermia.md
  enchants/ironspirit.md
  enchants/lunarstrike.md
  enchants/magic.md
  enchants/narcotic.md
  enchants/omniscient.md
  enchants/outrage.md
  enchants/peacekeeper.md
  enchants/permaflame.md
  enchants/raise.md
  enchants/reborn.md
  enchants/reflect.md
  enchants/reset.md
  enchants/revive.md
  enchants/rust.md
  enchants/soulsteal.md
  enchants/split.md
  enchants/steelbones.md
  enchants/strike.md
  enchants/tsunami.md
  enchants/vampire.md
Labels: documentation, enhancement
