Repository HisteriaMC/histeria-wiki, pull requests merged in 2023-10, with the labels that each got.

#146 Add some items
  .assets/blocks/cobblestone.png
  .assets/blocks/drawer.png
  .assets/items/apple.png
  .assets/items/compressed-cobblestone.png
  .assets/items/drawer-upgrade.png
  .assets/items/histerite-apple.png
  .assets/items/histerite-key.png
  .assets/items/vote-key.png
  items/compressed-cobblestone.md
  items/drawer-upgrade.md
  items/histerite-apple.md
  items/histerite-key.md
  items/vote-key
Labels: documentation

#168 Correction cercle V2
  objets/compressed-cobblestone.md
  objets/drawer-upgrade.md
  objets/histerite-apple.md
  objets/histerite-key.md
  objets/vote-key.md
Labels: bug, documentation

#169 Update compressed-cobblestone.md
  objets/compressed-cobblestone.md
Labels: bug, documentation

#170 MAJ liens ajouts cercle
  objets/compressed-cobblestone.md
  objets/drawer-upgrade.md
  objets/histerite-key.md
  objets/vote-key.md
Labels: bug, documentation

#171 Ajouts de blocs
  .assets/blocks/oak-wood.png
  .assets/blocks/spike.png
  .assets/blocks/white-wool.png
  .assets/items/diamond.png
  blocs/drawer.md
  blocs/elevator.md
  blocs/spike.md
Labels: documentation

#175 Ajouts de blocs
  .assets/blocks/elevator.png
  blocs/drawer.md
  blocs/elevator.md
Labels: documentation

#181 Ajouts d'items
  .assets/items/histerite-core.png
  .assets/items/nocturite-fruit.png
  .assets/items/nocturite-key.png
  .assets/items/nocturite-seed.png
  objets/histerite-compress.md
  objets/histerite-core.md
  objets/histerite-stick.md
  objets/histerite.md
  objets/nocturite-compress.md
  objets/nocturite-core.md
  objets/nocturite-crystal.md
  objets/nocturite-fruit.md
  objets/nocturite-key.md
  objets/nocturite-seed.md
Labels: documentation, enhancement, MVP

#185 Ajout des fossils
  .assets/blocks/chest.png
  .assets/items/punching-ball.png
  .assets/items/seed-planter.png
  .assets/pictures/cracked-stone.png
  .assets/pictures/fish.png
  .assets/pictures/shell.png
  .assets/pictures/skull.png
  .assets/pictures/stone-vein.png
  objets/fossils.md
Labels: documentation, enhancement, MVP

#183 Ajouts items
  .assets/items/grapnel.png
  .assets/items/item-pack.png
  .assets/items/magic-lyre.png
  .assets/items/thunderbolt.png
  objets/item-pack.md
  objets/magic-lyre.md
  objets/obsidian-breaker.md
  objets/punching-ball.md
  objets/seed-planter.md
  objets/zeus-flash.md
  outils/grapnel.md
Labels: documentation, enhancement, MVP

#188 Enchants pickaxe
  enchantements/archeologie.md
  enchantements/clean.md
  enchantements/compressor.md
  enchantements/infuse.md
Labels: documentation, enhancement

#189 Enchants sword/axe
  enchantements/berserk.md
  enchantements/corrupt.md
  enchantements/cryogenize.md
  enchantements/execution.md
  enchantements/lift.md
  enchantements/meteor.md
  enchantements/strike.md
Labels: documentation, enhancement

#190 Fix ajouts
  .assets/items/obsidian-breaker.png
  objets/fossils.md
  objets/obsidian-breaker.md
  objets/zeus-flash.md
Labels: bug

#192 Fix obsi breaker
  objets/obsidian-breaker.md
Labels: bug
