Repository HisteriaMC/histeria-wiki, pull requests merged in 2024-01, with the labels that each got.

#229 Update punching-ball.md
  objets/punching-ball.md
Labels: bug, enhancement

#228 Update item-pack.md
  objets/item-pack.md
Labels: bug, enhancement

#225 update du hood helmet & magic lyre
  .assets/items/hood-helmet.png
  .assets/items/magic-lyre.png
Labels: enhancement

#233 Update du coffre d'arène
  mondes/arena-chest.md
Labels: bug, enhancement

#218 Update histerite-core.md
  objets/histerite-core.md
Labels: bug, documentation

#235 Commande /settings
  commandes/settings-command.md
Labels: documentation, enhancement

#227 Rendu 3D des blocks
  .assets/blocks/cactus.png
  .assets/blocks/cave-block.png
  .assets/blocks/chest.png
  .assets/blocks/cobblestone.png
  .assets/blocks/dirt.png
  .assets/blocks/drawer.png
  .assets/blocks/elevator.png
  .assets/blocks/fertilized-dirt.png
  .assets/blocks/glass.png
  .assets/blocks/gold-block.png
  .assets/blocks/histerite-anvil.png
  .assets/blocks/histerite-block.png
  .assets/blocks/histerite-ore.png
  .assets/blocks/iron-block.png
  .assets/blocks/lucky-block.png
  .assets/blocks/nocturite-block.png
  .assets/blocks/oak-wood.png
  .assets/blocks/obsidian.png
  .assets/blocks/poison-obsidian.png
  .assets/blocks/random-ore.png
  .assets/blocks/renforced-obsidian.png
  .assets/blocks/spike.png
  .assets/blocks/white-wool.png
  .assets/items/drawer-upgrade.png
Labels: enhancement

#257 Craft sac à dos et planeur
  objets/hang-glider.md
  objets/item-pack.md
Labels: bug

#256 Icon Fossils
  .assets/icons/fossil.webp
  objets/fossils.md
Labels: enhancement, validate
